### ISSUE TITLE
Capabilities List filters for AvailablePhoneNumbers resource don't work AT ALL

### ISSUE THREAD

**Issue by ethanwillis** [twilio/twilio-node#344] opened 2018-05-18 04:17 UTC
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

3.17.0

### Code Snippet
```node
return new Promise((resolve, reject) => {
			return this.twilioclient.availablePhoneNumbers('US')
				.local.list({
          mmsEnabled: 'false'
        })
	.then(resolve)
	.catch(reject);
});
```

```node
return new Promise((resolve, reject) => {
			return this.twilioclient.availablePhoneNumbers('US')
				.local.list({
          voiceEnabled: 'false'
        })
	.then(resolve)
	.catch(reject);
});
```

```node
return new Promise((resolve, reject) => {
			return this.twilioclient.availablePhoneNumbers('US')
				.local.list({
          smsEnabled: 'false'
        })
	.then(resolve)
	.catch(reject);
});
```

### Exception/Log
```
{
        "friendlyName": "(440) 434-3519",
        "phoneNumber": "+14404343519",
        "lata": "320",
        "locality": "Lorain",
        "rateCenter": "LORAIN",
        "latitude": 41.4528,
        "longitude": -82.1824,
        "region": "OH",
        "postalCode": "44052",
        "isoCountry": "US",
        "addressRequirements": "none",
        "beta": false,
        "capabilities": {
            "voice": true,
            "SMS": true,
            "MMS": true,
            "fax": false
        }
    },
```

### Steps to Reproduce
1. Request a list of available phone numbers for purchase using either the voiceEnabled, smsEnabled, or mmsEnabled list filters.
2. Observe that the list of phone numbers returns phone numbers with capabilities.voice, capabilities.SMS, or capabilities.MMS return true when they should return false depending on which code snippet you run.

**Comment by dkundel** [comment] 2018-05-18 09:15
Hi @ethanwillis,

Sorry for the caused confusion. What's your use case for explicitly not wanting a feature? All of our US local numbers support SMS, voice and MMS. This feature is also more meant to explicitly request a feature rather than explicitly *not* request a feature. For example if you need a phone number that supports Fax you could do:

```js
twilioclient.availablePhoneNumbers('US').local.list({
  faxEnabled: true
})
.then(numbers => console.log(numbers))
.catch(err => console.error(err))
```

I don't see any harm in having a phone number that has more features supported than I would need. But maybe you have a use case for that and I would love to know about it. Until then I'll close this issue :)

PS:
The Twilio helper library already returns a Promise by default. Therefore there is no need for the `new Promise((resolve, reject) => {})` wrapping. You can simply write:
```js
return this.twilioclient.availablePhoneNumbers('US')
  .local.list({
     voiceEnabled: true
  });
```
And get the same result as you currently have without the overhead of creating another promise :)

**Closed by dkundel** 2018-05-18 09:15 UTC

**Comment by dkundel** [comment] 2018-05-18 18:10
Well this is more the underlining functionality that you would also find in the Twilio Console. It's more a filter to search for explicit functionality rather than not wanting a functionality. I'm still trying to see the use case in that. Why would you want a phone number that explicitly *doesn't* support a feature. I mean you don't have to use that feature just because it exists.

**Comment by ethanwillis** [comment] 2018-05-18 20:06
Even if the use case is in question, the fact that it doesn't work as advertised actually makes it completely redundant right? So why even allow people to search for true/false as a filter if it's just always going to return true? (Except in the case of Fax capabilities)

**Comment by ethanwillis** [comment] 2018-05-18 20:08
Actually I just checked and I'm getting back mixed true/false for faxEnabled when I pass faxEnabled = 'false'
So even in the case where a capability is not always available.. the filter is not working.

**Comment by ethanwillis** [comment] 2018-05-18 20:17
Also, where do I report issues with the api docs?

If we do 

```node
return this.twilioclient.availablePhoneNumbers('US')
    .local.list({
        AreaCode: "901"
    })
    .then(resolve)
    .catch(reject);
```

Numbers are returned with non 901 area codes.

However if we do 
```node
return this.twilioclient.availablePhoneNumbers('US')
    .local.list({
        areaCode: "901"
    })
    .then(resolve)
    .catch(reject);
```

It works correctly. "AreaCode" is correct for the cURL examples, but for all of the programming libraries we must use "areaCode" (And the same for any property name). However the table in the API docs spells all of the property names in the "capitalize" every word format. Not a huge deal, but its very inconsistent and should be a small change to fix.. since all of these client libraries must internally be sending "AreaCode" and not "areaCode".. or for example "MmsEnabled" and not "mmsEnabled."

**Comment by dkundel** [comment] 2018-05-22 06:28
Hi Ethan,

For your `areaCode` question. Yes the helper libraries adjust the name of the properties based on the programming language to make them more familiar for the respect developers. So in the case of JavaScript that means switching everything from `PascalCase` to `camelCase`. In other languages this would switch to `snake_case` for example. The Developer Education team is working on improving the API References for this as we agree that this can be confusing.

Back to your original issue. On the one hand the function would expect an actual boolean here. On the other hand this is as I mentioned before a functionality that is meant to explicitly *only* show numbers that *support* a feature. I.e. this flag is never meant to be used the other way around. This works the same way as in the Twilio Console. If you log into the [Twilio Console](https://www.twilio.com/console) and search for phone numbers there you'll be able to search for specific capabilities as well. If you check the checkbox "SMS" you'll only get phone numbers that have SMS definitely enabled. However, you'll notice that the other checkboxes are not ticked. That doesn't mean that the phone numbers would *only* support SMS. The flags in the API work the exact same way. I hope this clarifies the feature a bit more.

As I said before if you have a use case that you could elaborate on for the functionality that you explicitly *not* want a certain capability, I'm happy to forward it to the API team for consideration.

**Comment by ethanwillis** [comment] 2018-05-22 07:36
If this is how it's going to work then I guess it's really just an issue of documentation all around.

See documentation examples below. I get why false is a possible value, but there should be a note that false does not limit to only false values. 

![image](https://user-images.githubusercontent.com/182492/40348192-84a85d52-5d68-11e8-819b-1e34fc92f01b.png)

![image](https://user-images.githubusercontent.com/182492/40348238-b2a44540-5d68-11e8-84cb-ddf87f7f7699.png)

![image](https://user-images.githubusercontent.com/182492/40348247-bc0494dc-5d68-11e8-982c-481c5981fe5c.png)

**Comment by ethanwillis** [comment] 2018-05-22 07:42
In any case let's do a hypothetical where I'm running an application that needs HIPAA compliance. Say we don't want the risk of patients/prospects/clients sending sensitive health information to an SMS enabled phone number. In that case we would explicitly not want an SMS/MMS enabled number. In fact we wouldn't even want a Fax enabled number. 

Ideally for a call tracking application we'd want a voice only application with no voice recording. Even outside of a HIPAA context for general security/privacy reasons we may not want SMS/MMS/Fax enabled numbers in general just to reduce the surface area of how our numbers are interacted with.

**Comment by ethanwillis** [comment] 2018-05-22 08:33
Another issue/use case that I just came up with has to do with issue #342 and problems Ive seen with spam callers in my current industry coupled with the Twilio pricing model.

We want a mixture of MMS/SMS enabled numbers. But for the numbers where we don't want SMS we wouldn't want to pay to receive SMS from spammers. 

![image](https://user-images.githubusercontent.com/182492/40350973-dc897c9c-5d70-11e8-9b08-f8f1328bf863.png)

**Comment by gelinger777** [comment] 2021-05-20 20:34
sorry for offtopic question, but can you maybe hint how in api of twillio we could get list of supported cities with their area codes to use in the number request?
