### ISSUE TITLE
validateExpressRequest not working correctly

### ISSUE THREAD

**Issue by blazmrak** [twilio/twilio-node#657] opened 2021-02-17 12:15 UTC
### Issue Summary
There is a duality in the validator code for [validateExpressRequest](https://github.com/twilio/twilio-node/blob/ffbace7dd3605e09d5861c9e2488e6bdb8c6115b/lib/webhooks/webhooks.js#L147) as [validateRequest](https://github.com/twilio/twilio-node/blob/ffbace7dd3605e09d5861c9e2488e6bdb8c6115b/lib/webhooks/webhooks.js#L178) requires body parameter to be an object, but [validateRequestWithBody](https://github.com/twilio/twilio-node/blob/ffbace7dd3605e09d5861c9e2488e6bdb8c6115b/lib/webhooks/webhooks.js#L171) requires body to be a string. validateRequestWithBody is also called with 
```node
request.body || {}
```
so it fails even when body is not present.

### Steps to Reproduce
1. call validateExpressRequest with a request which has a parsed body object or no body at all

### Exception
If not before, exception occurs in [getExpectedBodyHash](https://github.com/twilio/twilio-node/blob/ffbace7dd3605e09d5861c9e2488e6bdb8c6115b/lib/webhooks/webhooks.js#L84) because body is not a string

### Technical details:
* twilio-node version: 3.56.0
* node version: 15.0.1

**Comment by shwetha-manvinkurke** [comment] 2021-02-17 23:19
@blazmrak Thanks for reporting. This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

[Internal tracking ](https://issues.corp.twilio.com/browse/DI-1201)

**Comment by blazmrak** [comment] 2021-02-18 08:16
@shwetha-manvinkurke I have fixed it locally by stringifying the body object in [getExpectedBodyHash](https://github.com/twilio/twilio-node/blob/ffbace7dd3605e09d5861c9e2488e6bdb8c6115b/lib/webhooks/webhooks.js#L84):
```node
.update(Buffer.from(JSON.stringify(body), 'utf-8'))
```
But to me this seems relatively ugly, because the request must also be edited in Flows for this to work (whitespaces have to be removed, because json body validation on backend executes on a raw string as far as I can tell). I'm relatively new to twilio, but I feel like this problem is more of a problem with how validation is working in general than the specific bug in the client code.

**Comment by shwetha-manvinkurke** [comment] 2021-03-10 16:32
@blazmrak Can you walk me through your use case? You shouldn't have to update `getExpectedBodyHash`. The idea here is so the users can use `validateExpressRequest` for their express app when the webhooks are configured for the Twilio phone number. The callback then could be a GET or a POST. In case of a POST request, the body of the request would be a string and the [query parameter bodySHA256 will be included in the request](https://www.twilio.com/docs/usage/security) and hence that check in `validateExpressRequest`. The only issue I see is in this line - `request.body || {}` if we assume there won't be a body, which is again not the case since that request will always have a body. It would help to understand what exactly you are trying to do.

**Comment by blazmrak** [comment] 2021-03-10 17:04
The body of the request is not a string, but an object, because it gets parsed. Your library expects it to be an object, because you also pass request.body to validateRequest function which only takes objects.

Also, the body does not need to be included, because the http request could serve as some sort of event trigger/custom call status webhook (this is not my usecase, but it could probably be used before the call gets diverted for example). 

The workaround we used to not make json requests.

**Comment by shwetha-manvinkurke** [comment] 2021-03-10 21:48
Alrighty, I could reproduce this issue and am working on a fix. Will keep you updated!

**Comment by shwetha-manvinkurke** [comment] 2021-03-11 16:32
@blazmrak I tried a couple of things -
1. I created a Studio Flow and in one of my steps, I set up a HTTP POST webhook with content type as `Application/JSON` and in my express app, I did a `app.use(bodyParser.json())` and I could reproduce the issue that you saw. Meaning, the `webhook()/validateExpressRequest()` will fail because the body is not a string. I then did a `JSON.stringify(request.body)` in the `validateExpressRequest` and that works when there is are no whitespaces in the request body. If there are whitespaces, then the bodySHA wouldn’t match the hash that we calculate in `getExpectedBodyHash`. Basically, I ran through all the steps that you did. 
2. Secondly, I set up a HTTP POST webhook directly in the console for my number and in my app, did a `app.use(bodyParser.urlencoded({ extended: true }));` and I could validate the request because in this case the content type is `application/x-www-form-urlencoded` and the validation logic is not the same as 1 as it does a `validateRequest` only.  

While there is no clean way to do the validation in the client library if the request is parsed as json or rather, there is no obvious way at all, the best approach you could take is to parse the body as a text/string if the content type is application/json. If you are using [body parser](https://www.npmjs.com/package/body-parser), this is what it would look like - 

```node
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.text({ type: "application/json" }));
```

If you do that, then you wouldn’t have a problem validating the webhooks. Let me know if you see a problem doing that. Also, let me know what parser you are using to parse the request.

**Comment by blazmrak** [comment] 2021-03-11 18:13
If I was to change the parser, all of my other endpoints and middleware would die... 

Also, having some bodies to be strings and some bodies to be objects seems incredibly inconsistent, especially in the language where types are a mystery anyways. It feels even uglier than the solution 1. 

I have no idea what your codebase on the backend looks like and I have no idea how you guys think other codebases look like, but I have not yet seen a codebase where the json request body is not parsed into some sort of an object and remained a string.

The problem is a bit with this library, because it does not stringify the object, but the way you hash the body on the backend stinks, because you guys don't remove the whitespaces before hashing it (you are replacing the values in the {{}} anyways, so there really wouldn't be much of a performance impact).

**Comment by shwetha-manvinkurke** [comment] 2021-03-11 21:24
@blazmrak we understand that there is a problem. We are not denying that and we _will_ work with the other internal teams to get more clarity on the hashing itself and why they don't trim the whitespaces. We are also checking with the Studio team itself (assuming that's what you are using) to see if it's possible for them to trim the request body. In the meantime, would it be reasonable to ask you to feed in the raw body of the request into our library by doing something like [this](https://flaviocopes.com/express-get-raw-body/) since we need the raw body for our validation? I understand that's not _the_ most ideal solution but that would work if we change our library code to parse the `request.rawBody` instead for the body validation.

**Comment by blazmrak** [comment] 2021-03-12 07:21
Yeah, this should work and not interfere with any of the existing code.

**Closed** 2021-03-15 17:26 UTC
Labels: status: help wanted, type: bug
