### ISSUE TITLE
TypeScript Error: `Beep` is the wrong type, should be boolean 

### ISSUE THREAD

**Issue by evanhuang8** [twilio/twilio-node#378] opened 2018-08-29 22:40 UTC
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

This 

**Version:**

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
<place exception/log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by dkundel** [comment] 2018-08-30 09:11
Closing because it's a duplicate of #379

**Closed by dkundel** 2018-08-30 09:11 UTC
