### ISSUE TITLE
validateRequest, validateExpressRequest return false when HTTP request has a deep path

### ISSUE THREAD

**Issue by cgarrovillo** [twilio/twilio-node#650] opened 2021-01-26 04:43 UTC
### Issue Summary
Because of the way that `validateRequest` & `validateExpressRequest` are implemented,  rebuilding the full URL using the request yields a different string than the "real" full URL.

"Real" URL:  `https://ef648da1957b.ngrok.io/organization/us-central1/sms/test`
Built URL: `http://ef648da1957b.ngrok.io/test`

-----
This is mainly because of the use of `request.originalUrl`,  where only the very last child path is returned (`/test`) and not everything after the host (`/organization/us-central1/sms/test`).

Therefore causing unequal hashes.

**Built URL** (using request.originalUrl)
![image](https://user-images.githubusercontent.com/6688713/105802692-f2312580-5f58-11eb-96a8-a1b543ae56af.png)

**Real URL**
![image](https://user-images.githubusercontent.com/6688713/105802581-b72ef200-5f58-11eb-94ed-1a41d0437015.png)

signature & headers match when the full url is passed.

### Steps to Reproduce
1. Create a String object containing your "**real**" full url.  (ie. `const url = 'https://ef648da1957b.ngrok.io/organization/us-central1/sms/test'  `)
2. Invoke the `twilio.validateExpressRequest()` function, passing in the `request` object and your `authToken`.
3. Invoke the `twilio.validateRequest()` function, now using the "**real**" full url String you created above,  also passing in an empty `parameter` object for simplicity.  `twilio.validateRequest(`${authToken}`, twilioSignature, fullUrl, {})`
4. Compare results between two.

### Code Snippet
```node
export const testValidation = (request: any, response: any) => {
  const authToken = process.env.TWILIO_AUTH || ''

  const realUrl = `https://ef648da1957b.ngrok.io/organization/us-central1/sms/test`
  const twilioSignature = request.get('X-Twilio-Signature') || ''

  const expectedMock = getExpectedTwilioSignature(authToken, realUrl, {})

  const validateUsingRequest = client.validateExpressRequest(request, authToken)
  const validateUsingRealUrl = client.validateRequest(`${authToken}`, twilioSignature, realUrl, {})

  console.log(validateUsingRequest)   // false
  console.log(validateUsingRealUrl)   // true
  console.log(expectedMock === twilioSignature)  // true
}
```

### Exception/Log
```
>false
>true
>true
```

### Technical details:
* twilio-node version: ^3.55.0
* node version: 12.20.1

**Comment by shwetha-manvinkurke** [comment] 2021-01-26 23:51
@cgarrovillo, Thanks for reporting the issue. [request.originalUrl](http://expressjs.com/en/api.html#req.originalUrl) should return the baseURL+path. I am going to try and reproduce the issue and get back to you.

**Comment by cgarrovillo** [comment] 2021-01-27 21:00
> @cgarrovillo, Thanks for reporting the issue. [request.originalUrl](http://expressjs.com/en/api.html#req.originalUrl) should return the baseURL+path. I am going to try and reproduce the issue and get back to you.

Thanks for looking into it.
It looks like it's very inconsistent at the moment. There are times when we use baseUrl that it also only returns the last part of the path, and times where everything is returned.

node version: 12.18.4 on Google Cloud

**Comment by cgarrovillo** [comment] 2021-01-28 21:56
I might close this one soon. This is starting to look like an Express/Google Cloud problem instead of Twilio:
[https://github.com/firebase/firebase-functions/issues/854](https://github.com/firebase/firebase-functions/issues/854)

If nobody has any more input feel free to close it.

**Comment by JenniferMah** [comment] 2021-01-28 22:27
Hi @cgarrovillo I'm going to go ahead and close this because it doesn't look like it's a Twilio Node library issue. Please feel free to open a new issue if you encounter any other problems using the Twilio Node library.

**Closed by JenniferMah** 2021-01-28 22:27 UTC
Labels: type: non-library issue
